# Generated by Django 4.2.16 on 2026-04-23 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción del programa y su objetivo')),
                ('area', models.IntegerField(help_text='Área del conocimiento 1-5 según SUB')),
                ('grado_previsto', models.CharField(blank=True, choices=[('LIC', 'Licenciatura'), ('TUS', 'Técnico Univ. Superior'), ('TEC', 'Técnico'), ('OTRO', 'Otro')], help_text='Grado al que aspira convertirse cuando sea carrera oficial', max_length=5)),
                ('estado', models.CharField(choices=[('FORMULACION', 'En Formulación'), ('APROBACION', 'En Aprobación'), ('IMPLEMENTACION', 'En Implementación'), ('SUSPENDIDO', 'Suspendido')], default='FORMULACION', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_prevista_aprobacion', models.DateField(blank=True, help_text='Fecha estimada para convertirse en carrera oficial', null=True)),
                ('resolucion_hcu', models.CharField(blank=True, max_length=100)),
                ('resolucion_ran', models.CharField(blank=True, max_length=100)),
                ('numero_sub', models.IntegerField(blank=True, help_text='Número SUB si ya tiene asignado', null=True)),
                ('responsable', models.CharField(blank=True, help_text='Docente o comisión responsable del programa', max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='universidades.sede')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['sede__facultad__universidad__sigla', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrograma',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción del programa y su objetivo')),
                ('area', models.IntegerField(help_text='Área del conocimiento 1-5 según SUB')),
                ('grado_previsto', models.CharField(blank=True, choices=[('LIC', 'Licenciatura'), ('TUS', 'Técnico Univ. Superior'), ('TEC', 'Técnico'), ('OTRO', 'Otro')], help_text='Grado al que aspira convertirse cuando sea carrera oficial', max_length=5)),
                ('estado', models.CharField(choices=[('FORMULACION', 'En Formulación'), ('APROBACION', 'En Aprobación'), ('IMPLEMENTACION', 'En Implementación'), ('SUSPENDIDO', 'Suspendido')], default='FORMULACION', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_prevista_aprobacion', models.DateField(blank=True, help_text='Fecha estimada para convertirse en carrera oficial', null=True)),
                ('resolucion_hcu', models.CharField(blank=True, max_length=100)),
                ('resolucion_ran', models.CharField(blank=True, max_length=100)),
                ('numero_sub', models.IntegerField(blank=True, help_text='Número SUB si ya tiene asignado', null=True)),
                ('responsable', models.CharField(blank=True, help_text='Docente o comisión responsable del programa', max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='universidades.sede')),
            ],
            options={
                'verbose_name': 'historical Programa',
                'verbose_name_plural': 'historical Programas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
