# Generated by Django 4.2.16 on 2026-08-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsede',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción general de la sede, historia, servicios, etc.'),
        ),
        migrations.AddField(
            model_name='historicalsede',
            name='imagen_referencia',
            field=models.TextField(blank=True, help_text='Foto del edificio, campus, entrada u otra imagen de referencia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción general de la sede, historia, servicios, etc.'),
        ),
        migrations.AddField(
            model_name='sede',
            name='imagen_referencia',
            field=models.ImageField(blank=True, help_text='Foto del edificio, campus, entrada u otra imagen de referencia', null=True, upload_to='sedes/imagenes/%Y/'),
        ),
        migrations.AlterField(
            model_name='historicalsede',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsede',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
