# Generated by Django 4.2.16 on 2026-04-23 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo_sistema',
            field=models.BooleanField(default=False, help_text='True cuando el admin aprueba la cuenta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('RECTOR', 'Rector'), ('VICERRECTOR', 'Vicerrector'), ('DECANO', 'Decano'), ('DIRECTOR', 'Director de Carrera'), ('TECNICO_DSA', 'Técnico DSA'), ('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante'), ('ADMINISTRATIVO', 'Administrativo'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento de Bolivia donde trabaja', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento_identidad',
            field=models.CharField(blank=True, help_text='CI o carnet institucional', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='motivo_solicitud',
            field=models.TextField(blank=True, help_text='Por qué solicita acceso al sistema'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadministrador SUB'), ('ADMIN_DSA', 'Administrador DSA'), ('TECNICO', 'Técnico Curricular'), ('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante'), ('PENDIENTE', 'Pendiente de aprobación')], default='PENDIENTE', max_length=20),
        ),
    ]
