# Generated by Django 4.2.16 on 2026-06-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_activo_sistema_usuario_aprobado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador', models.CharField(blank=True, max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_activa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión Activa',
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('VER', 'Ver registro'), ('CREAR', 'Crear registro'), ('EDITAR', 'Editar registro'), ('ELIMINAR', 'Eliminar registro'), ('EXPORTAR', 'Exportar datos'), ('OTRO', 'Otra acción')], max_length=15)),
                ('modulo', models.CharField(help_text='App o sección donde ocurrió la acción', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('objeto_repr', models.CharField(blank=True, help_text='Representación del objeto afectado', max_length=300)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
