# Generated by Django 4.2.16 on 2026-04-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('medio_verificacion_default', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proceso', models.CharField(choices=[('REDISENO', 'Rediseño Curricular'), ('DISENO', 'Diseño Curricular'), ('COMPLEMENTACION', 'Complementación Curricular'), ('ACTUALIZACION', 'Actualización Curricular'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre_proceso', models.CharField(blank=True, max_length=300)),
                ('anio_inicio', models.IntegerField()),
                ('anio_conclusion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('CONCLUIDO', 'Concluido'), ('ARCHIVADO', 'Archivado')], default='EN_PROCESO', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='carreras.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalProcesoCurricular',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_proceso', models.CharField(choices=[('REDISENO', 'Rediseño Curricular'), ('DISENO', 'Diseño Curricular'), ('COMPLEMENTACION', 'Complementación Curricular'), ('ACTUALIZACION', 'Actualización Curricular'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre_proceso', models.CharField(blank=True, max_length=300)),
                ('anio_inicio', models.IntegerField()),
                ('anio_conclusion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('CONCLUIDO', 'Concluido'), ('ARCHIVADO', 'Archivado')], default='EN_PROCESO', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('carrera', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carreras.carrera')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proceso curricular',
                'verbose_name_plural': 'historical proceso curriculars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FaseProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_conclusion', models.DateField(blank=True, null=True)),
                ('medio_verificacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='seguimiento.procesocurricular')),
                ('tipo_fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguimiento.tipofase')),
            ],
        ),
    ]
