# Generated by Django 4.2.16 on 2026-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faseproceso',
            name='archivo_verificacion',
            field=models.FileField(blank=True, help_text='Sube el documento que verifica esta fase (PDF, Word, Excel)', null=True, upload_to='verificacion_fases/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='historicalprocesocurricular',
            name='tipo_proceso',
            field=models.CharField(choices=[('DISENO', 'Diseño Curricular'), ('REDISENO', 'Rediseño Curricular'), ('AJUSTE', 'Ajuste Curricular'), ('COMPLEMENTACION', 'Complementación Curricular'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='procesocurricular',
            name='tipo_proceso',
            field=models.CharField(choices=[('DISENO', 'Diseño Curricular'), ('REDISENO', 'Rediseño Curricular'), ('AJUSTE', 'Ajuste Curricular'), ('COMPLEMENTACION', 'Complementación Curricular'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
