# Generated by Django 4.2.16 on 2026-04-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('programa', models.CharField(blank=True, max_length=300)),
                ('area', models.IntegerField(help_text='Área del conocimiento 1-5 según SUB')),
                ('grado', models.CharField(choices=[('LIC', 'Licenciatura'), ('TUS', 'Técnico Univ. Superior'), ('TEC', 'Técnico'), ('OTRO', 'Otro')], max_length=5)),
                ('tipo', models.CharField(choices=[('C', 'Carrera'), ('D', 'Departamento/Programa')], max_length=2)),
                ('diploma_academico', models.CharField(blank=True, max_length=300)),
                ('titulo_profesional', models.CharField(blank=True, max_length=300)),
                ('enfoque_curricular', models.CharField(blank=True, choices=[('OBJETIVOS', 'Por Objetivos'), ('COMPETENCIAS', 'Por Competencias'), ('OTRO', 'Otro')], max_length=15)),
                ('en_funcionamiento', models.BooleanField(default=True)),
                ('numero_sub', models.IntegerField(blank=True, help_text='Número correlativo nacional SUB', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='universidades.sede')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_aprobacion', models.IntegerField()),
                ('evento_aprobacion', models.CharField(blank=True, max_length=100)),
                ('resolucion_hcu', models.CharField(blank=True, max_length=100)),
                ('resolucion_ran', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='carreras.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCarrera',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('programa', models.CharField(blank=True, max_length=300)),
                ('area', models.IntegerField(help_text='Área del conocimiento 1-5 según SUB')),
                ('grado', models.CharField(choices=[('LIC', 'Licenciatura'), ('TUS', 'Técnico Univ. Superior'), ('TEC', 'Técnico'), ('OTRO', 'Otro')], max_length=5)),
                ('tipo', models.CharField(choices=[('C', 'Carrera'), ('D', 'Departamento/Programa')], max_length=2)),
                ('diploma_academico', models.CharField(blank=True, max_length=300)),
                ('titulo_profesional', models.CharField(blank=True, max_length=300)),
                ('enfoque_curricular', models.CharField(blank=True, choices=[('OBJETIVOS', 'Por Objetivos'), ('COMPETENCIAS', 'Por Competencias'), ('OTRO', 'Otro')], max_length=15)),
                ('en_funcionamiento', models.BooleanField(default=True)),
                ('numero_sub', models.IntegerField(blank=True, help_text='Número correlativo nacional SUB', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='universidades.sede')),
            ],
            options={
                'verbose_name': 'historical carrera',
                'verbose_name_plural': 'historical carreras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
