# Generated by Django 4.2.16 on 2026-04-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['nombre'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='historicalcarrera',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Carrera', 'verbose_name_plural': 'historical Carreras'},
        ),
        migrations.AlterModelOptions(
            name='planestudio',
            options={'ordering': ['-anio_aprobacion'], 'verbose_name': 'Plan de Estudio', 'verbose_name_plural': 'Planes de Estudio'},
        ),
    ]
